# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 2.2.{build}
configuration: Release
platform: Any CPU

build:
  project: src\prover.sln
  verbosity: normal
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
branches:
  only:
    - master
    - prod
artifacts:
  - path: build
    name: prover-v$(appveyor_build_version)
services:
  - mssql2014           # start SQL Server 2014 Express

deploy:
# Deploy to GitHub Releases
- provider: GitHub
  tag: v$(APPVEYOR_BUILD_VERSION)
  release: v$(APPVEYOR_BUILD_VERSION)
  description: 'Prover release - v$(APPVEYOR_BUILD_VERSION)'
  auth_token:
    secure: GUR7LqjBnoRB5BGTUhRrE4Wc+ZyV3eAkDXe2S7gMbmeGN0t2gpAR0x+3jA1LWvKlXAsB8jyPil0HBD1SYFnDXkq9cIFnxTGxax47RUzbNxk=
  on:
    branch: master
